[package]
name = "repak"
version = "0.1.0"
authors = ["Berkus Decker <berkus+crates@metta.systems>"]
description = "REPAK asset library format support"
edition = "2024"
repository = "https://github.com/berkus/repak"
license = "MIT OR Apache-2.0"
keywords = ["games", "assets"]
categories = [
    "filesystem",
    "development-tools",
    "game-development",
    "parser-implementations",
]

[features]
default = ["all-checksums", "all-compression", "all-encryption"]
all-compression = [
    "compress-deflate",
    "compress-bzip",
    "compress-zstd",
    "compress-lzma",
    "compress-lz4",
]
compress-deflate = ["dep:flate2"]
compress-bzip = ["dep:bzip2"]
compress-zstd = ["dep:zstd"]
compress-lzma = ["dep:xz2"]
compress-lz4 = ["dep:lz4"]
all-encryption = ["encrypt-adiantum", "encrypt-threefish", "encrypt-xts"]
encrypt-adiantum = ["dep:adiantum", "dep:aes", "dep:cipher", "dep:chacha20"]
encrypt-threefish = ["dep:threefish", "dep:cipher"]
encrypt-xts = ["dep:xts-mode", "dep:aes", "dep:cipher"]
# encrypt-hctr2 = ["dep:hctr2"] # not working yet
all-checksums = [
    "checksum-sha3",
    "checksum-k12",
    "checksum-blake3",
    "checksum-xxhash3",
    "checksum-seahash",
    "checksum-cityhash",
]
checksum-sha3 = ["dep:tiny-keccak"]
checksum-k12 = ["dep:tiny-keccak"]
checksum-blake3 = ["dep:blake3"]
checksum-xxhash3 = ["dep:twox-hash"]
checksum-seahash = ["dep:seahash"]
checksum-cityhash = ["dep:cityhash-rs"]

[dependencies]
blake3 = { version = "1.8", optional = true }
bzip2 = { version = "0.6", optional = true }
byteorder = "1.5.0"
cityhash-rs = { version = "1.0", optional = true }
culpa = "1.0.2"
flate2 = { version = "1.1", optional = true }
leb128 = "0.2.5"
lz4 = { version = "1.28", optional = true }
seahash = { version = "4.1", optional = true }
tempfile = "3.20.0"
thiserror = "2.0.12"
tiny-keccak = { version = "2.0", features = ["sha3", "k12"], optional = true }
two_phase_interner = { version = "0.1.0", path = "../two_phase_interner" } # TODO: remove the path dep
twox-hash = { version = "2.1", features = ["xxhash3_128"], optional = true }
xz2 = { version = "0.1", optional = true }
zstd = { version = "0.13", optional = true }
adiantum = { version = "0.1.3", optional = true }
threefish = { version = "0.5.2", optional = true }
xts-mode = { version = "0.5.1", optional = true }
aes = { version = "0.8", optional = true }
cipher = { version = "0.4", optional = true }
chacha20 = { version = "0.9", optional = true }
# Really, just don't use this (it's a mess):
#hctr2 = { version = "0.3.0", optional = true, git = "https://github.com/berkus/hctr2-rs", branch = "fixes" }

[dev-dependencies]
anyhow = "1.0.98"
argh = "0.1.13"
const-hex = "1.14.1"
serde = "1.0.219"
serde_json = "1.0.141"
